### ISSUE TITLE
Version 1.9.0 testing as replacement in CXF soap project gives this runtime error

### ISSUE THREAD

**Issue by mdiskin** [librewsdl4j/libre-wsdl4j#11]
```
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=CONFIGURATION_ERROR: No Java extensionType found to represent a '{http://www.w3.org/2001/XMLSchema}schema' element in the context of a 'javax.wsdl.Types'.
	at javax.wsdl.extensions.ExtensionRegistry.createExtension(ExtensionRegistry.java:231) ~[libre-wsdl4j-1.9.0.jar:na]
	at org.apache.cxf.wsdl11.ServiceWSDLBuilder.getSchemaImplementation(ServiceWSDLBuilder.java:284) ~[cxf-rt-wsdl-3.5.3.jar:3.5.3]
```

**Comment by andreasrosdal** [comment]
Thank you for reporting. Pull requests welcome.

**Comment by rzo1** [comment]
Next release will ix this @mdiskin
