### ISSUE TITLE
Exception while reading WSDL if <wsdl:portType><wsp:Policy> is found 

### ISSUE THREAD

**Issue by tcarlson2000** [librewsdl4j/libre-wsdl4j#4]
Error thrown when <wsdl:portType><wsp:Policy> is found while reading WSDL

Caused by: WSDLException (at /wsdl:definitions/wsdl:portType/wsp:Policy): faultCode=INVALID_WSDL: Encountered unexpected element '{http://schemas.xmlsoap.org/ws/2004/09/policy}Policy'.:
        at com.ibm.wsdl.util.xml.DOMUtils.throwWSDLException(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.parsePortType(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.parseDefinitions(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        ... 53 more
WSDLException (at /wsdl:definitions/wsdl:portType/wsp:Policy): faultCode=INVALID_WSDL: Encountered unexpected element '{http://schemas.xmlsoap.org/ws/2004/09/policy}Policy'.:
   

...
	<wsdl:portType name="ImportDeclarationNotification_In">
		<wsdl:documentation>
			<sapdoc:sapdoc xmlns:sapdoc="urn:sap:esi:documentation">
				<sapdoc:docitem applicationComponent="SLL-LEG"/>
			</sapdoc:sapdoc>
		</wsdl:documentation>
		<wsp:Policy>
			<wsp:PolicyReference URI="#IF__ImportDeclarationNotification_In"/>
		</wsp:Policy>
		<wsdl:operation name="ImportDeclarationNotification_In">
			<wsp:Policy>
				<wsp:PolicyReference URI="#OP__ImportDeclarationNotification_In"/>
			</wsp:Policy>
			<wsdl:input message="tns:ImportDeclarationNotification"/>
		</wsdl:operation>
	</wsdl:portType>
...

**Comment by andreasrosdal** [comment]
Thanks for reporting. Pull requests welcome!

**Comment by rzo1** [comment]
This is not reproducable. Added a test in https://github.com/librewsdl4j/libre-wsdl4j/commit/91a4d1d59f3f3ca629e53ab010a6bd778d01b526
